### ISSUE TITLE
临时爆破许可证申请

### ISSUE THREAD

**Issue by 580820** [WeaveStudio-of-UYXA/TianyuServer#6]
玩家<bbb>备于<2022年10月1日>至<2023年1月1日>期间，在<地狱>世界坐标(512,128,367)至(639,0,240)之间实施<自动>成规模爆破施工，主要施工玩家当前账户剩余音符数为<137463>，因<建筑>工程需要，申请此证。

**Comment by tsingyayin** [comment]
审核通过，允许在上述范围和时间内实施爆破作业
